### PR TITLE
WIP: Chore/postgres local dev

### LINKED ISSUE #289: switch local dev to use postgres rather than sqlite
using sqlite for local dev has been easy, but now we have production / staging deployments which use postgres, we are encountering some bugs / crashes when deploying due to the differences between sqlite and postgres.

this ticket is to change connection config to postgres, along with a guide to getting cobuy running locally on MacOS / Linux.

### PR DESCRIPTION
**Pull request by iainkirkpatrick**
closes #289 

todo:
- [X] connection params to use postgres rather than sqlite
- [x] guide for macOS and Linux users

NB. currently running the app assumes you have a database in your local Postgres installation named `cobuy_development`. The guide will show users how to create this db, but could also be cool if possible to have an npm script (`npm run init`?) that does that, plus migrate, seed etc for them

### CODE REVIEW

**Comment by iainkirkpatrick** [comment]
using the [dogstack guide for postgres setup](https://dogstack.js.org/guides/how-to-setup-sql-db.html) for now - for me on MacOS it really is as simple as installing postgres App, can someone confirm the process in that guide for Linux and then that Cobuy local dev works as expected with the new connection params? @ahdinosaur @NotThatSmith

**Comment by michael-smith-nz** [comment]
@iainkirkpatrick  I've just added a password field for this to work, but the `burnthedb` script no longer works. I attempted to fix it myself, but my lack of postgres knowledge was showing. We can discuss at sprint planning

**Comment by iainkirkpatrick** [comment]
@NotThatSmith interesting:

- was the password field required for connecting to the database on linux? i didn't seem to need one...
- when `burnthedb` fails, is that something in the migrations or seeds?

File: tasks/services/works.js [hunk 1]
```diff
@@ -222,14 +222,17 @@ function createCastOrderIntentTaskWorks (hook) {
...
+          taskRecipeId: 'castIntent'
+          // TODO: IK: can't compare JSON values in postgres, need another way to do it
+          // params: {
+          //   $like: `%"orderId":${orderId}%`
+          // }
         }
       })
         .then((taskPlans) => {
-          return Promise.all(taskPlans.map((taskPlan) => {
+          // TODO: IK: can't compare JSON values in postgres, need another way to do it
```
Comment (ahdinosaur) [inline tasks/services/works.js:233]: https://www.postgresql.org/docs/current/static/functions-json.html

**Comment by ahdinosaur** [comment]
> when `burnthedb` fails, is that something in the migrations or seeds?

the first thing done by `burnthedb` is remove the sqlite database file, so that part will no longer work.

fix incoming!

File: tasks/services/works.js (hunk 1 above)
Comment (ahdinosaur) [reply tasks/services/works.js:233]: @iainkirkpatrick i did a thing! [`queryByOrder`](https://github.com/root-systems/cobuy/blob/a38b8f61b7255024d95fc7c5e364696e21cefe3c/tasks/hooks/queryByOrder.js)

Comment (iainkirkpatrick) [reply tasks/services/works.js:233]: oooh damn im intrigued to learn this wizardry @ahdinosaur 🎉 🎉 🎉
